### PR TITLE
Refactored core code to make it modular and readable

### PR DESCRIPTION
**Pull request by shubhamoli**
File: battery_wall.sh

Changes:
- Made code more modular using functions
- Migrated if-elif equality based logic to division based
- removed exec call, instead called main function infintely

Important:
- Code is not tested as I don't have a machine right now (only cloud native VMs)

### CODE REVIEW

**Comment by adi1090x** [comment]
good, but it doesn't work.

**Comment by shubhamoli** [comment]
> good, but it doesn't work.

Now please check. 

Fixed:
- `get_battery` and `is_charging` are treated as commands instead of plain strings
- `animate_wall` undefined issue

**Comment by shubhamoli** [comment]
Since, PR #3 is merged now i can test my code it in my mac:

Thanks @sfroment for the PR

Meanwhile, I've to refactor my code and resolve conflicts

**Comment by sfroment** [comment]
@shubhamoli btw do not forget to run the ```brew install wallpaper```

**Comment by adi1090x** [comment]
i would love to use your code, if  you can... add MacOS support too.
at least i don't have to *exec* the script, also improve the **main** function.
@sfroment did a good job. hope you'll too.

**Comment by adi1090x** [comment]
> Since, PR #3 is merged now i can test my code it in my mac:
> 
> Thanks @sfroment for the PR
> 
> Meanwhile, I've to refactor my code and resolve conflicts

I've updated the code, merged your's too.

**Pull request closed without merging**
